Document: openframeworks
Title: Debian openframeworks Manual
Author: <insert document author here>
Abstract: This manual describes what openframeworks is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openframeworks/openframeworks.sgml.gz

Format: postscript
Files: /usr/share/doc/openframeworks/openframeworks.ps.gz

Format: text
Files: /usr/share/doc/openframeworks/openframeworks.text.gz

Format: HTML
Index: /usr/share/doc/openframeworks/html/index.html
Files: /usr/share/doc/openframeworks/html/*.html
